Changed return type from parse_json_response
RedHatQE/rosa-python-client pull request #11
Opened 2023-06-01 11:41 UTC by oharan2

2023-06-01 14:29 UTC, myakove commented
/hold

2023-06-01 18:52 UTC, rnetser approved these changes

2023-06-05 10:29 UTC, oharan2 commented
/verified

2023-06-05 12:58 UTC, myakove commented on rosa/cli.py
> +        json or dict: json if json.loads(res.stdout) not fail,
pleas rephrased, you always return dict
I think we always need to return the same structure in the dict
{"stdout": ......, "stderr": .....}

2023-06-05 13:01 UTC, myakove requested changes

2023-06-05 13:01 UTC, myakove commented on rosa/cli.py
> +        json or dict: json if json.loads(res.stdout) not fail,
{"out": ......, "err": .....}

2023-06-05 14:00 UTC, oharan2 commented
/verified

2023-06-06 07:53 UTC, myakove requested changes

2023-06-06 08:15 UTC, oharan2 commented on rosa/cli.py
> +        "out": _try_json_load(response.stdout),
Check separately if any one of stdout/stderr could pass json.loads

2023-06-06 08:15 UTC, oharan2 commented
/verified

2023-06-07 18:41 UTC, oharan2 commented
/verified

2023-06-08 08:11 UTC, myakove commented
/hold cancel

2023-06-08 08:12 UTC, myakove approved these changes

2023-06-08 08:12 UTC, merged