Raise multiple places if not logged
RedHatQE/rosa-python-client pull request #25
Opened 2023-06-25 06:16 UTC by oharan2

2023-06-25 06:18 UTC, oharan2 commented
/verified

2023-06-25 07:19 UTC, omrirh approved these changes

2023-06-25 09:56 UTC, myakove requested changes

2023-06-25 09:56 UTC, myakove commented on rosa/cli.py
> +            "Not logged in to OCM, either pass 'token' or log in before running."
Please remove the msg from here and let the caller send it
This will not fit when raising it from line 34 since you already send the token

2023-06-26 10:01 UTC, oharan2 commented
Resolved in #29

2023-06-26 10:01 UTC, closed without merging