Add get rosa-versions function
RedHatQE/rosa-python-client pull request #270
Opened 2024-09-13 13:49 UTC by chetna14manku

2024-09-13 13:49 UTC, redhat-qe-bot2 commented
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
    * You can add extra args to the Podman build command
        * Example: `/build-and-push-container --build-arg OPENSHIFT_PYTHON_WRAPPER_COMMIT=<commit_hash>`
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`
 * To assign reviewers based on OWNERS file use `/assign-reviewers`
 * To check if PR can be merged use `/check-can-merge`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest tox`: Retest tox
 * `/retest python-module-install`: Retest python-module-install

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

2024-09-13 19:17 UTC, myakove requested changes

2024-09-13 19:17 UTC, myakove commented on rosa/rosa_versions.py
> +    Get all rosa versions for specified channel group.
Please add empty line before `Args:`

2024-09-13 19:17 UTC, myakove commented on rosa/rosa_versions.py
> +    rosa_base_available_versions_dict = {}
Please set typing

2024-09-13 19:17 UTC, myakove commented on rosa/rosa_versions.py
> +    _all_versions = [ver["raw_id"] for ver in base_available_versions]
ditto

2024-09-15 08:59 UTC, myakove approved these changes

2024-09-15 09:15 UTC, chetna14manku commented
/verified

2024-09-15 09:26 UTC, rnetser approved these changes

2024-09-15 09:26 UTC, merged