Update pyproject.toml
RedHatQE/rosa-python-client pull request #71
Opened 2023-07-31 13:50 UTC by oharan2

2023-07-31 20:47 UTC, myakove requested changes
Please update the PR title to be more informative and add more info in the first comment

2023-07-31 20:47 UTC, myakove commented on pyproject.toml
>  version = "1.0.28"
version should be 0.0.0
And you should have a VERSION file with 1.0.28

2023-07-31 20:47 UTC, myakove commented on pyproject.toml
>  ipdb = "^0.13.13"
Add ipython

2023-08-02 07:16 UTC, oharan2 commented on pyproject.toml
>  ipdb = "^0.13.13"
Done

2023-08-02 07:17 UTC, oharan2 commented
/verified

2023-08-02 07:24 UTC, myakove requested changes
PR title is not updated, update it

File `.release-it.json` should be change to handle the VERSION file

```
"plugins": {
    "@j-ulrich/release-it-regex-bumper": {
      "out": [
        {
          "files": [
            "pyproject.toml"
          ],
          "search": "version = \"\\d+\\.\\d+\\.\\d+\"",
          "replace": "version = \"{{version}}\""
        }
      ]
    }
```
should be replaced with 

```
"plugins": {
    "@release-it/bumper": {
      "in": "VERSION",
      "out": "VERSION"
    }
  }

```

please update `release-it` section in the README
`npm install --save-dev @release-it/bumper` should be execute outside the repository directory (I think ~/ is good place)

2023-08-02 12:58 UTC, rnetser commented
> Please update the PR title to be more informative and add more info in the first comment

not addressed

2023-08-02 13:00 UTC, rnetser requested changes

2023-08-02 13:00 UTC, rnetser commented on pyproject.toml
> +target_version = ['py37', 'py38', 'py39', 'py310', "py311"]
please remove `py37`

2023-08-02 13:00 UTC, rnetser commented on pyproject.toml
> +[tool.black]
https://github.com/RedHatQE/rosa-python-client/pull/71#pullrequestreview-1558368463 is not addressed

2023-08-03 10:34 UTC, oharan2 commented
/verified

2023-08-03 15:56 UTC, rnetser approved these changes

2023-08-03 16:23 UTC, myakove approved these changes

2023-08-03 16:26 UTC, merged